name: mantra
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
channel_priority: strict
dependencies:
  - python=3.10
  - pip
  - pytorch
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - anndata
  - scanpy>=1.9
  - h5py
  - pyarrow
  - numba
  - umap-learn
  - leidenalg
  - statsmodels
  - seaborn
  - pip:
      - mypy
      - types-requests
      - rich
      - tqdm